version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "80:80"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
      networks:
   app_net:
        # use the bridge driver, but enable IPv6
        driver: default
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                gateway: 172.16.238.1
               
