version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "80:80"
      - "40000:49999"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
